Repository HendrikPN/scigym-api, pull requests merged in 2019-09, with the labels that each got.

#29 Returning errors to frontend for environment form
  scigym/environments/serializers.py
  scigym/environments/views.py
Labels: MVP, enhancement, frontend

#30 Admin Model for ImageConfig
  scigym/config/admin.py
Labels: MVP, backend

#31 Added new images
  static/images/APIforScience.png
  static/images/CPUforScience.png
  static/images/RLforScience.png
Labels: enhancement

#32 Feature/forum
  scigym/config/common.py
  scigym/environments/migrations/0016_environment_url.py
  scigym/environments/migrations/0017_auto_20190926_1030.py
  scigym/environments/migrations/0018_auto_20190926_1058.py
  scigym/environments/models.py
  scigym/environments/serializers.py
  scigym/environments/views.py
  scigym/forums/__init__.py
  scigym/forums/admin.py
  scigym/forums/migrations/0001_initial.py
  scigym/forums/migrations/0002_auto_20190916_1111.py
  scigym/forums/migrations/0003_auto_20190925_0950.py
  scigym/forums/migrations/0004_auto_20190926_0841.py
  scigym/forums/migrations/0005_auto_20190926_1058.py
  scigym/forums/migrations/__init__.py
  scigym/forums/models.py
  scigym/forums/serializers.py
  scigym/forums/views.py
  scigym/repositories/migrations/0007_repository_readme_name.py
  scigym/repositories/models.py
  scigym/repositories/serializers.py
  scigym/repositories/utils.py
  scigym/urls.py
  scigym/users/permissions.py
  scigym/utils/github.py
Labels: MVP, backend, enhancement
